### ISSUE TITLE
Regexp Lookbehind not support with safari

### ISSUE THREAD

**Issue by Najtu** [DanielJDufour/get-epsg-code#7]
The code uses regexp Lookbehind which is not supported by safari. This cause safari to error out during rendering.

https://caniuse.com/js-regexp-lookbehind

**Comment by DanielJDufour** [comment]
Thank you for reporting this bug @Najtu !  Would you be interested in contributing a solution via pull request?

**Comment by DanielJDufour** [comment]
Hi, @Najtu .  This should be fixed now with recent changes.  Could you try again and let me know if this fixed it for you?  Thank you again for bringing this to our attention :-)
